# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_user_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_frequency',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
