# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='country',
            field=models.CharField(default='Ireland', max_length=200),
        ),
        migrations.AddField(
            model_name='credit',
            name='payment_location',
            field=models.CharField(default='On-site', max_length=200),
        ),
        migrations.AddField(
            model_name='credit',
            name='payment_type',
            field=models.CharField(default='Paypal', max_length=200),
        ),
    ]
